Support deploy on docker swarm
ctripcorp/apollo pull request #3558
Opened 2021-02-20 06:40 UTC by aibeb

## What's the purpose of this PR

XXXXX

## Which issue(s) this PR fixes:
Fixes #

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [ ] Read the [Contributing Guide](https://github.com/ctripcorp/apollo/blob/master/CONTRIBUTING.md) before making this pull request.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Write necessary unit tests to verify the code.
- [ ] Run `mvn clean test` to make sure this pull request doesn't break anything.

2021-02-21 08:29 UTC, nobodyiam requested changes

2021-02-21 08:29 UTC, nobodyiam commented on scripts/apollo-on-swarm/README.md
> +  --env apollo_admin-service_url=http://apollo-adminservice:8090 \
Environment variables are normally in upper case.

```suggestion
  --env APOLLO_CONFIG_SERVICE_URL=http://${apollo-configservice-url}:8080 \
  --env APOLLO_ADMIN_SERVICE_URL=http://${apollo-adminservice-url}:8090 \
```

2021-02-21 08:29 UTC, nobodyiam commented on scripts/apollo-on-swarm/application-github.properties
> +# DataSource
Looks like this file is not used?

2021-02-21 08:29 UTC, nobodyiam commented on scripts/apollo-on-swarm/docker-compose.yml
> +      - apollo_config-service_url=http://localhost:8080
the same suggestion as above

2021-02-21 08:29 UTC, nobodyiam commented on scripts/apollo-on-swarm/README.md
> +  apolloconfig/apollo-configservice
is it better to add a version here?
```suggestion
  apolloconfig/apollo-configservice:${version}
```

2021-02-21 08:29 UTC, nobodyiam commented on docs/zh/deployment/distributed-deployment-guide.md
> +[docker swarm部署](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-swarm/README.md)
Is it better to put the detailed instructions here?

2021-02-23 11:03 UTC, aibeb commented on scripts/apollo-on-swarm/application-github.properties
> +# DataSource
谢谢反馈。
该文件在README.md的60行使用到了
在docker-compose.yml的19行使用到了
需要该文件是因为 该文件被绑定给容器用于覆盖默认的apolloconfig/apollo-configservice镜像的application-github.properties，目的是为了让apolloconfig/apollo-configservice读取到环境变量apollo.config-service.url，apollo.admin-service.url

2021-02-23 11:04 UTC, aibeb commented on scripts/apollo-on-swarm/README.md
> +  apolloconfig/apollo-configservice
感谢反馈，我会添加version

2021-02-23 11:04 UTC, aibeb commented on scripts/apollo-on-swarm/docker-compose.yml
> +      - apollo_config-service_url=http://localhost:8080
会修复

2021-02-23 11:06 UTC, aibeb commented on docs/zh/deployment/distributed-deployment-guide.md
> +[docker swarm部署](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-swarm/README.md)
放在这里是因为 distributed-deployment-guide.md 太长了，感觉放进去阅读障碍。
我倒是建议把k8s的也单独放到k8s到文件夹的README中可好？

看你的意见哈，希望得到反馈

2021-02-23 11:11 UTC, aibeb commented on scripts/apollo-on-swarm/README.md
> +  --env apollo_admin-service_url=http://apollo-adminservice:8090 \
这里会改成大写
另: 由于swarm集群内部，可以直接访问。这里的APOLLO_ADMIN_SERVICE_URL我理解只是为了给portal使用，
portal与admin，config在同一个集群所以可以直接写http://apollo-adminservice:8090。

我会采用你建议的格式，同时增加注释，以防用户使用不清。

当然也存在不在同一集群的情况，这里我没有给出示例。

最终集群对外只需要暴露 config的8080端口 以及portal的8070端口即可。

2021-02-23 11:11 UTC, aibeb commented on docs/zh/deployment/distributed-deployment-guide.md
> +[docker swarm部署](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-swarm/README.md)
等确定这个文档地址存放处，我再重新提交一个pr哈～

2021-02-23 11:12 UTC, closed without merging

2021-02-23 11:27 UTC, aibeb commented on scripts/apollo-on-swarm/README.md
> +  apolloconfig/apollo-configservice
看了下k8s也没有添加version，具体可见scripts/helm/apollo-service/values.yaml
其实不加version默认取latest，这里本来也是demo，version不加可否

2021-02-24 00:12 UTC, nobodyiam commented on scripts/apollo-on-swarm/README.md
> +  apolloconfig/apollo-configservice
k8s 是有加的，我建议加上吧，可以让用户有意识的感知到版本号

https://github.com/ctripcorp/apollo/blob/0a7b76023641c6fb1e18aea845296a4b3e6276ad/scripts/helm/apollo-service/templates/deployment-configservice.yaml#L53-L55

2021-02-24 00:12 UTC, nobodyiam commented on scripts/apollo-on-swarm/README.md
> +  --env apollo_admin-service_url=http://apollo-adminservice:8090 \
恩，admin service 可以保持默认值，不需要用户修改

2021-02-24 00:14 UTC, nobodyiam commented on docs/zh/deployment/distributed-deployment-guide.md
> +[docker swarm部署](https://github.com/ctripcorp/apollo/blob/master/scripts/apollo-on-swarm/README.md)
good point...let me think about it

2021-02-24 00:16 UTC, nobodyiam commented on scripts/apollo-on-swarm/application-github.properties
> +# DataSource
环境变量已经通过 ENV 传进去了，所以这个文件 mount 到容器里面应该是没啥作用的吧？
除非我们期望用户通过配置文件而不是 ENV 的方式配置数据库连接串、apollo.config-service.url等？

2021-02-24 02:54 UTC, aibeb commented on scripts/apollo-on-swarm/README.md
> +  apolloconfig/apollo-configservice
接受你的建议，我会添加在下一个pr中

2021-02-24 02:55 UTC, aibeb commented on scripts/apollo-on-swarm/application-github.properties
> +# DataSource
加为了保持变量名保持SPRING_DATASOURCE_URL风格，其实可以不用加。直接用APOLLO.CONFIG-SERVICE.URL环境变量。接受你的建议，我下一个PR会去掉application-github.properties